name: 🐞 Bug Report
description: Tell us about something that's not working the way we (probably) intend.
labels: ["Kind:Bug", "State:Triage"]
body:
  - type: input
    id: elixir-version
    attributes:
      label: Elixir version
      description: Use `elixir -v` to find the Elixir version.
    validations:
      required: true

  - type: input
    id: aba-file-validator-version
    attributes:
      label: aba-file-validator version
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: How can we reproduce what you're seeing? Include code samples, errors and stacktraces if appropriate.
      placeholder: |-
        1. foo
        2. bar
        3. baz
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
    validations:
      required: true
