name: Auto release package

on:
  release:
    types: [published]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish_package:
    if: github.event_name == 'release'
    name: Publish to hex.pm
    runs-on: ubuntu-latest
    env:
      HEX_API_KEY: ${{secrets.HEX_API_KEY}}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add release version to VERSION.txt
      run: echo ${{ github.ref_name }} > VERSION.txt

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: 1.14
        otp-version: 24.2
    - name: Install dependencies
      run: mix deps.get 
      
    - name: Publish package
      run: mix hex.publish --yes