name: Release package

on:
  release:
    types: [published]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish_package:
    name: Publish to hex.pm
    runs-on: ubuntu-latest
    env:
      HEX_API_KEY: ${{secret.HEX_API_KEY}}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: 1.0
        otp-version: 24.2

    - name: Run tests
      run: mix hex.publish --yes