name: Auto release package

on:
  workflow_dispatch:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  release:
    types: [published]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish_package:
    name: Publish to hex.pm
    runs-on: ubuntu-latest
    env:
      HEX_API_KEY: ${{secrets.HEX_API_KEY}}

    steps:
      - name: Checkout
        run: echo ${{github.ref_name}}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Add release version to VERSION.txt
        run: echo ${{ github.ref_name }} > VERSION.txt

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.14
          otp-version: 24.2
      - name: Install dependencies
        run: mix deps.get

      - name: Publish package
        run: mix hex.publish --yes
